name: yukimi
description: Anime/Manga command-line interface backed up by Tenka.
version: 1.0.0

publish_to: none

environment:
    sdk: ">=2.15.0-226.0.dev <3.0.0"

dependencies:
    args: ^2.3.0
    collection: ^1.15.0
    colorize: ^3.0.0
    dl: ^1.0.5
    http: ^0.13.4
    mime_type: ^1.0.0
    path: ^1.8.0
    shlex: ^2.0.2
    tenka:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_tenka
    utilx:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_utilx
    utilx_desktop:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_utilx_desktop

dev_dependencies:
    devx:
        git:
            url: git://github.com/yukino-org/packages.git
            ref: dart_devx
    lint: ^1.5.3
